package mapreduce

import (
	"encoding/json"
	"hash/fnv"
	"io/ioutil"
	"log"
	"os"
)

// doMap manages one map task: it reads one of the input files
// (inFile), calls the user-defined map function (mapF) for that file's
// contents, and partitions the output into nReduce intermediate files.
func doMap(
	jobName string, // the name of the MapReduce job
	mapTaskNumber int, // which map task this is
	inFile string,
	nReduce int, // the number of reduce task that will be run ("R" in the paper)
	mapF func(file string, contents string) []KeyValue,
) {
	//
	// You will need to write this function.
	//
	// The intermediate output of a map task is stored as multiple
	// files, one per destination reduce task. The file name includes
	// both the map task number and the reduce task number. Use the
	// filename generated by reduceName(jobName, mapTaskNumber, r) as
	// the intermediate file for reduce task r. Call ihash() (see below)
	// on each key, mod nReduce, to pick r for a key/value pair.
	//
	// mapF() is the map function provided by the application. The first
	// argument should be the input file name, though the map function
	// typically ignores it. The second argument should be the entire
	// input file contents. mapF() returns a slice containing the
	// key/value pairs for reduce; see common.go for the definition of
	// KeyValue.
	//
	// Look at Go's ioutil and os packages for functions to read
	// and write files.
	//
	// Coming up with a scheme for how to format the key/value pairs on
	// disk can be tricky, especially when taking into account that both
	// keys and values could contain newlines, quotes, and any other
	// character you can think of.
	//
	// One format often used for serializing data to a byte stream that the
	// other end can correctly reconstruct is JSON. You are not required to
	// use JSON, but as the output of the reduce tasks *must* be JSON,
	// familiarizing yourself with it here may prove useful. You can write
	// out a data structure as a JSON string to a file using the commented
	// code below. The corresponding decoding functions can be found in
	// common_reduce.go.
	//
	//   enc := json.NewEncoder(file)
	//   for _, kv := ... {
	//     err := enc.Encode(&kv)
	//
	// Remember to close the file after you have written all the values!
	//
	//fmt.Println("inside doMap:")
	dat, err := ioutil.ReadFile(inFile)
	if err != nil {
		log.Fatal(err)
	}
	content := string(dat)

	wordMap := mapF(inFile, content)
	//totalSize := len(wordMap)

	//fmt.Println("first 10 words->", wordMap[1:100])
	//fmt.Println("number of reducers:", nReduce)
	//enc := make([]json.NewEncoder, nReduce)
	// open nReduce files to save the intermediate results
	//encFiles := make(map[string]json.Encoder)

	for i := 0; i < nReduce; i++ {
		//fmt.Println("Reduce Task:", i)
		f, err := os.Create(reduceName(jobName, mapTaskNumber, i))
		if err != nil {
			log.Fatal("create intermediate reduce files: ", err)
		}
		//encFiles[reduceName(jobName, mapTaskNumber, i)] = json.NewEncoder(f)
		enc := json.NewEncoder(f)

		for _, kv := range wordMap {
			r := ihash(kv.Key) % nReduce
			if r == i {
				err := enc.Encode(&kv)
				if err != nil {
					log.Fatal("write to reduce files: ", err)
				}
			}
		}
		f.Close()
	}
	//indexing := make(map[int]KeyValue)

	//for i := 0; i < nReduce; i++ {
	//	rFiles[i].Close
	//}
}

func ihash(s string) int {
	h := fnv.New32a()
	h.Write([]byte(s))
	return int(h.Sum32() & 0x7fffffff)
}
